version: '3.8'

services:
  postgres:
    container_name: pokemonPostgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: poke_user
      POSTGRES_PASSWORD: poke_password
      POSTGRES_DB: poke_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-multi-db.sh:/docker-entrypoint-initdb.d/init-multi-db.sh:ro
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: pokemon_redis
    ports:
      - "6379:6379"
    restart: always
volumes:
  postgres_data:
