"""add moves in captured pokemon

Revision ID: 019bc581c8ca
Revises: a898ab3856e8
Create Date: 2026-03-03 12:36:14.892204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '019bc581c8ca'
down_revision: Union[str, Sequence[str], None] = 'a898ab3856e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captured_pokemon_moves',
    sa.Column('captured_pokemon_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('move_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['captured_pokemon_id'], ['captured_pokemons.id'], ),
    sa.PrimaryKeyConstraint('captured_pokemon_id', 'move_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captured_pokemon_moves')
    # ### end Alembic commands ###
