"""create type table

Revision ID: 588d6dfd3a87
Revises: db8e8d7e53b9
Create Date: 2026-02-18 16:22:33.806056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588d6dfd3a87'
down_revision: Union[str, Sequence[str], None] = 'db8e8d7e53b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text_color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('background_color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('type_weaknesses',
    sa.Column('type_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('weakness_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['weakness_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('type_id', 'weakness_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_weaknesses')
    op.drop_table('types')
    # ### end Alembic commands ###
