"""create captured pokemon table

Revision ID: 7adb81402ebc
Revises: e7e8afa159e0
Create Date: 2026-02-18 17:03:58.722027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7adb81402ebc'
down_revision: Union[str, Sequence[str], None] = 'e7e8afa159e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captured_pokemons',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('iv_hp', sa.Integer(), nullable=False),
    sa.Column('ev_hp', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('battles', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('iv_speed', sa.Integer(), nullable=False),
    sa.Column('ev_speed', sa.Integer(), nullable=False),
    sa.Column('iv_attack', sa.Integer(), nullable=False),
    sa.Column('ev_attack', sa.Integer(), nullable=False),
    sa.Column('iv_defense', sa.Integer(), nullable=False),
    sa.Column('ev_defense', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('iv_special_attack', sa.Integer(), nullable=False),
    sa.Column('ev_special_attack', sa.Integer(), nullable=False),
    sa.Column('iv_special_defense', sa.Integer(), nullable=False),
    sa.Column('ev_special_defense', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('pokemon_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trainer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captured_pokemons')
    # ### end Alembic commands ###
