"""update type table

Revision ID: a898ab3856e8
Revises: 269ad0f1e3ea
Create Date: 2026-02-26 14:57:55.974690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a898ab3856e8'
down_revision: Union[str, Sequence[str], None] = '269ad0f1e3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_strengths',
    sa.Column('type_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('strengths_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['strengths_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('type_id', 'strengths_id')
    )
    op.alter_column('pokemon', 'growth_rate_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pokemon', 'growth_rate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('type_strengths')
    # ### end Alembic commands ###
