"""create user table

Revision ID: e494843245ad
Revises: eb28092efaa8
Create Date: 2026-02-18 16:57:13.789845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e494843245ad'
down_revision: Union[str, Sequence[str], None] = 'eb28092efaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
              DO $$ BEGIN
                  CREATE TYPE statusenum AS ENUM ('ACTIVE', 'COMPLETE', 'INACTIVE', 'INCOMPLETE');
              EXCEPTION
                  WHEN duplicate_object THEN null;
              END $$;
          """)
    op.execute("""
            DO $$ BEGIN
                CREATE TYPE roleenum AS ENUM ('ADMIN', 'USER');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """)

    op.execute("""
            DO $$ BEGIN
                CREATE TYPE genderenum AS ENUM ('MALE', 'FEMALE', 'OTHER');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """)

    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='roleenum', create_type=False),nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='genderenum', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'COMPLETE', 'INACTIVE', 'INCOMPLETE', name='statusenum', create_type=False), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('pokeballs', sa.Integer(), nullable=False),
    sa.Column('capture_rate', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('total_authentications', sa.Integer(), nullable=False),
    sa.Column('last_authentication_at', sa.DateTime(), nullable=False),
    sa.Column('authentication_success', sa.Integer(), nullable=False),
    sa.Column('authentication_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
