"""create pokedex table

Revision ID: e7e8afa159e0
Revises: e494843245ad
Create Date: 2026-02-18 17:02:22.461656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e8afa159e0'
down_revision: Union[str, Sequence[str], None] = 'e494843245ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokedex',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('iv_hp', sa.Integer(), nullable=False),
    sa.Column('ev_hp', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('battles', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('iv_speed', sa.Integer(), nullable=False),
    sa.Column('ev_speed', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('iv_attack', sa.Integer(), nullable=False),
    sa.Column('ev_attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('iv_defense', sa.Integer(), nullable=False),
    sa.Column('ev_defense', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('special_attack', sa.Integer(), nullable=False),
    sa.Column('iv_special_attack', sa.Integer(), nullable=False),
    sa.Column('ev_special_attack', sa.Integer(), nullable=False),
    sa.Column('special_defense', sa.Integer(), nullable=False),
    sa.Column('iv_special_defense', sa.Integer(), nullable=False),
    sa.Column('ev_special_defense', sa.Integer(), nullable=False),
    sa.Column('discovered', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('formula', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('pokemon_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trainer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokedex')
    # ### end Alembic commands ###
