"""create pokemon with relationship table

Revision ID: eb28092efaa8
Revises: 588d6dfd3a87
Create Date: 2026-02-18 16:41:52.302261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb28092efaa8'
down_revision: Union[str, Sequence[str], None] = '588d6dfd3a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
          DO $$ BEGIN
              CREATE TYPE statusenum AS ENUM ('ACTIVE', 'COMPLETE', 'INACTIVE', 'INCOMPLETE');
          EXCEPTION
              WHEN duplicate_object THEN null;
          END $$;
      """)

    op.create_table('pokemon',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('status',postgresql.ENUM('ACTIVE', 'COMPLETE', 'INACTIVE', 'INCOMPLETE', name='statusenum',create_type=False), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('habitat', sa.String(), nullable=True),
    sa.Column('is_baby', sa.Boolean(), nullable=True),
    sa.Column('shape_url', sa.String(), nullable=True),
    sa.Column('shape_name', sa.String(), nullable=True),
    sa.Column('is_mythical', sa.Boolean(), nullable=True),
    sa.Column('gender_rate', sa.Integer(), nullable=True),
    sa.Column('is_legendary', sa.Boolean(), nullable=True),
    sa.Column('capture_rate', sa.Integer(), nullable=True),
    sa.Column('hatch_counter', sa.Integer(), nullable=True),
    sa.Column('base_happiness', sa.Integer(), nullable=True),
    sa.Column('special_attack', sa.Integer(), nullable=True),
    sa.Column('external_image', sa.String(), nullable=False),
    sa.Column('base_experience', sa.Integer(), nullable=True),
    sa.Column('special_defense', sa.Integer(), nullable=True),
    sa.Column('evolution_chain_url', sa.String(), nullable=True),
    sa.Column('evolves_from_species', sa.String(), nullable=True),
    sa.Column('has_gender_differences', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('growth_rate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['growth_rate_id'], ['growth_rates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pokemon_abilities',
    sa.Column('pokemon_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ability_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'ability_id')
    )
    op.create_table('pokemon_evolutions',
    sa.Column('pokemon_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('evolution_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['evolution_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'evolution_id')
    )
    op.create_table('pokemon_moves',
    sa.Column('pokemon_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('move_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'move_id')
    )
    op.create_table('pokemon_types',
    sa.Column('pokemon_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_types')
    op.drop_table('pokemon_moves')
    op.drop_table('pokemon_evolutions')
    op.drop_table('pokemon_abilities')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
